//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Querying {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Querying.SeedResources", typeof(SeedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Salário
        ///2,Aluguel
        ///3,Academia
        ///4,Acessórios
        ///5,Almoço
        ///6,Animal de Estimação
        ///7,Açougue
        ///8,Bar/Balada
        ///9,Café/lanches
        ///10,Celular
        ///11,Cinema
        ///12,Combustível
        ///13,Ônibus
        ///14,Condomínio
        ///15,Cursos
        ///16,Dentista
        ///17,Eletrônicos
        ///18,Faculdade
        ///19,Futebol.
        /// </summary>
        internal static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, Credicard, 1, 1, 234
        ///2, Visa, 1, 2, 5124
        ///3, Banco do Nordeste, 2, 3, 2134
        ///4, Volkscard, 1, 4, 232
        ///5, Hipercard, 1, 5, 2345
        ///6, Bradesco, 2, 6, 234
        ///7, ChicoCard, 1, 2, 5476
        ///8, Bitcoin, 2, 4, 554
        ///9, Palmas, 1, 2, 353
        ///10, Itaú, 2, 1, 678
        ///.
        /// </summary>
        internal static string Contas {
            get {
                return ResourceManager.GetString("Contas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  1, 2019/1/1, Transação Financeira do dia 1/1/2019, 1, 8, 4, 8.09
        /// 2, 2019/1/1, Transação Financeira do dia 1/1/2019, 2, 17, 6, 54.8
        /// 3, 2019/1/1, Transação Financeira do dia 1/1/2019, 2, 6, 5, 53.12
        /// 4, 2019/1/1, Transação Financeira do dia 1/1/2019, 2, 3, 7, 25.22
        /// 5, 2019/1/1, Transação Financeira do dia 1/1/2019, 1, 10, 6, 58.09
        /// 6, 2019/1/1, Transação Financeira do dia 1/1/2019, 2, 7, 8, 36.64
        /// 7, 2019/1/1, Transação Financeira do dia 1/1/2019, 1, 17, 7, 19.53
        /// 8, 2019/1/1, Transação Financeira  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Movimentacao {
            get {
                return ResourceManager.GetString("Movimentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Cartão de Crédito
        ///2,Conta Corrente
        ///.
        /// </summary>
        internal static string TipoConta {
            get {
                return ResourceManager.GetString("TipoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, Débito
        ///2, Crédito
        ///.
        /// </summary>
        internal static string TipoMovimento {
            get {
                return ResourceManager.GetString("TipoMovimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Thanos,Rua Suécia, 2330, Maraponga, 60000000, CE, 1910-05-25
        ///2,Saitama, Trashed area, 12, Z City, 68485848, Z, 2000-06-22
        ///3,Naruto Uzumaki, Distrito Norte, 19, Silvermoon, 65545665, CE, 2000-07-23
        ///4,Kakashi Hatake, Vale da Força, 23, Ogrimar, 68485848, ce, 2000-08-24
        ///5,Anakim&apos;, Vale da Força, 33, Ogrimar, 68485848, ce, 2000-08-28
        ///6,Darth Lucas Skywalker, Vale da Força, 33, Ogrimar, 68485848, ce, 2000-08-28
        ///7,Minato Namikaze, Av. Santos Dumont, 2313, Fortaleza, 60000000, CE, 2000-09-25.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
